# Generated by Django 2.1.3 on 2018-11-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='source',
            name='is_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
