# Generated by Django 2.1.3 on 2018-11-20 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_weather', '0002_auto_20181119_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='weather',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weathers', to='my_weather.Source'),
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together={('source', 'date')},
        ),
    ]
