# Generated by Django 2.1.3 on 2018-11-20 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_weather', '0003_auto_20181120_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weathers', to='my_weather.Source', unique_for_date='date'),
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together=set(),
        ),
    ]
