# Generated by Django 2.1.3 on 2018-11-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_weather', '0004_auto_20181120_1331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together={('source', 'date')},
        ),
    ]
